### ISSUE TITLE
Alias Command does not update invalid command message

### ISSUE THREAD

**Issue by maxxyh** [AY2021S1-CS2103-W14-3/tp#99]
![image](https://user-images.githubusercontent.com/55223114/97499186-684cdd00-19a8-11eb-9be4-8c7dd6be2b3a.png)

Bug: remapped alias commands don't display their command when an invalid command is raised. Is this worth changing? Currently the SORT_KEYWORD is being used.

Steps to reproduce: 
1. Remap a command 
2. Invalid input using the new alias command

**Comment by ngmarcus** [comment]
If the alias was created by the user and the app is a single-user app, we safely assume that the user should understand the invalid command raised since he/she was the one who created the alias in the first place. We can also assume either one of the following scenarios:
- used the alias command intentionally to customise his input process
- mistakenly used alias command. For a beginner user of the feature, he can use resetAlias which is covered in the User Guide. For an experienced user of the feature, he can revert the specific alias using the alias command with reversed parameter.
